### ISSUE TITLE
HystrixPlugins.getInstance() returns private instance

### ISSUE THREAD

**Issue by sahlex** [Netflix/Hystrix#1390]
In Hystrix 1.5.5, when calling `HystrixPlugins.getInstance()` I get a 
```
java.lang.NoClassDefFoundError: Could not initialize class com.netflix.hystrix.strategy.HystrixPlugins$LazyHolder
```
exception in an OSGi environment.

In 1.4.x it worked without problems.
How is intended to work?

The private inner class effectively prevents the OSGi classloader to make it available to client bundles. As soon as I patch it to be publicly available, I can use the plugin mechanism again. As it worked fine in 1.4.x I'd consider this a defect.

**Comment by sahlex** [comment]
Right currently We are relying on Hystrix 1.5.6 so I provided a patch for this version. I guess the master is on 2.x already. The pull request is provided for the master - so myabe a backport to 1.5.7 is necessary?
Anywasy - thanks for the collaboration!

**Comment by agentgt** [comment]
Hmm that is bizarre. Are you sure it is OSGI because if Hystrix can't be initialized you will get that error on subsequent calls. 

> _In most JVM implementations, if construction of Something fails, subsequent attempts to initialize it from the same class-loader will result in a NoClassDefFoundError failure._ (see https://en.wikipedia.org/wiki/Initialization-on-demand_holder_idiom).

Which makes me concerned that OSGi is calling it more than once.

However because the error of `NoClassDefFoundError` is pretty bad regardless of OSGi perhaps the standard [double checked locking](https://en.wikipedia.org/wiki/Double-checked_locking) would be a better solution.

Thus I  don't recommend @sahlex  changes which will add yet another thing that is `public` (and thus effectively changing the API) but rather the a double checked locking instantiation. I was in fact going to do it this way original but thought it might be cleaner the lazy holder way.

**Comment by sahlex** [comment]
It turned out that after setting up the environment freshly, the exception does not appear any more.
So it seems that it popped up due to some OSGi class-loader mess.

Sorry for the inconvenience, please close the issue.

Thanks a lot anyways.

Alexander.

**Comment by wentfar** [comment]
I have met the same error:

_"Could not initialize class com.netflix.hystrix.strategy.HystrixPlugins$LazyHolder"_

env:jdk8

how to solve?

**Comment by wentfar** [comment]
I have met the same error:

"Could not initialize class com.netflix.hystrix.strategy.HystrixPlugins$LazyHolder"

env:
windows 10, jdk8, hystrix 1.5.12


how to solve?
